name: Scrape Energy Projects (AU East)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"   # ~1:00am Sydney during AEDT

permissions:
  contents: read

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # If you add JS-driven scrapers later:
      # - name: Install Playwright browsers
      #   run: |
      #     pip install playwright
      #     playwright install --with-deps

      - name: Run scraper (NSW + QLD first)
        run: |
          python run.py --states NSW QLD --sources nsw_major_projects qld_qtenders --query "solar OR wind OR energy" --limit 100

      - name: Upload CSV + DB
        uses: actions/upload-artifact@v4
        with:
          name: projects_snapshot-${{ github.run_id }}
          path: |
            data/projects_snapshot.csv
            data/projects.sqlite
          if-no-files-found: warn

